### ISSUE TITLE
Create Sponsors section

### ISSUE THREAD

**Issue by audrey-yang** [pennapps/2022f.pennapps#16]
Style according to the [Figma](https://app.slack.com/client/T036E8W4J/C03JAE7B1V0#:~:text=PennApps%20XXIII%20Iteration%20Site)

[Square logo](https://drive.google.com/file/d/1W7-AC0OeCAWnrgfYyquvBwAmNhf9s6nO/view)
[Banner (no date)](https://drive.google.com/file/d/1JT-dCHFerftqnJEkEDZbxSmA5GFgdYMq/view)
[Banner (with date)](https://drive.google.com/file/d/1t-2qSsP0O1H4kvfQPIFxa4PPSd2MnGwn/view)
[Other assets](https://drive.google.com/drive/folders/1PksmPXHBVvKcXNCAnMj3bemeJ1LKVbGG)

Can use a couple from [2021f.pennapps](https://github.com/pennapps/2021f.pennapps/tree/main/public/logos) for now.

**Comment by fyy26** [comment]
Closed with #32
